name: Branch Deleted
on: 
  delete
jobs:
  delete-deployment:
    if: contains(github.event.ref, 'update/') || contains(github.event.ref, 'preview/') || contains(github.event.ref, 'jimtest/')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Pipeline
        id: delete-deployment
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        with:
          # pass name of the branch deleted to CircleCI
          GHA_Meta: "${{ github.event.ref }}"
        env:
          # CircleCI API token
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
